FROM postgres:11

COPY ./backend-res/setup-jwt.sh /docker-entrypoint-initdb.d/

RUN chmod +x *.sh 

RUN apt-get update && \
    apt-get -y install git make postgresql-server-dev-11 bash

RUN mkdir /testdata

COPY ./backend-res/test-binaries/* /testdata/

RUN git clone https://github.com/michelp/pgjwt.git && cd pgjwt && make install

