grant all on api.documents to administrator;
grant usage, select on sequence api.documents_id_seq to administrator;
grant all on api.events to administrator;
grant usage, select on sequence api.events_id_seq to administrator;
grant all on api.tags to administrator;
grant usage, select on sequence api.tags_id_seq to administrator;
grant all on api.pages to administrator;
grant usage, select on sequence api.pages_id_seq to administrator;
grant all on api.news to administrator;
grant usage, select on sequence api.news_id_seq to administrator;